#!/usr/bin/env node
// Writes shared/wire/schema.json: a JSON Schema for every message on the WebSocket, both ways.
//
// Why it exists: the iOS app (docs/PLAN.md, D7) implements this protocol by hand in Swift, and a
// hand copy that nothing checks is forbidden. The schema and the golden fixtures beside it are
// what it is checked against, read in place from shared/wire/ so there is no second copy to drift.
//
// Generated from the BUILT shared package (shared/dist), not the TypeScript source, so this runs on
// plain Node with no loader. Run `npm run build:shared` first; `npm run gen:wire` does both.
//
// Deterministic by construction: object keys are sorted at every depth, arrays keep their source
// order (which is the order the union members and required fields are declared in), 2 space
// indent, one trailing newline. That is what lets check_wire.mjs compare the committed file to a
// fresh generation byte for byte instead of structurally.

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { zodToJsonSchema } from "zod-to-json-schema";

const HERE = dirname(fileURLToPath(import.meta.url));
export const REPO = join(HERE, "..");
export const WIRE = join(REPO, "shared", "wire");
const SHARED_DIST = join(REPO, "shared", "dist", "index.js");

/** The built shared package. Fails with the fix spelled out, not a module resolution trace. */
export async function loadShared() {
  if (!existsSync(SHARED_DIST)) {
    throw new Error(`${SHARED_DIST} does not exist. Run \`npm run build:shared\` first.`);
  }
  return import(pathToFileURL(SHARED_DIST).href);
}

function sortKeys(value) {
  if (Array.isArray(value)) return value.map(sortKeys);
  if (value !== null && typeof value === "object") {
    return Object.fromEntries(
      Object.keys(value)
        .sort()
        .map((key) => [key, sortKeys(value[key])]),
    );
  }
  return value;
}

/** The schema document, as the exact text that belongs in schema.json. */
export async function generateSchemaText() {
  const shared = await loadShared();

  // Named so a reader of the schema (and of any Swift written from it) sees one Member, one
  // RenderedLine, one code enum, referenced wherever it is used, rather than the same shape
  // inlined a dozen times with nothing saying the copies are the same type.
  const named = {
    dialectCode: shared.dialectCode,
    roomCode: shared.roomCode,
    username: shared.username,
    glossaryEntry: shared.glossaryEntry,
    errorCode: shared.errorCode,
    translationFailureCode: shared.translationFailureCode,
    translationStatus: shared.translationStatus,
    skipReason: shared.skipReason,
    rtcIceServerConfig: shared.rtcIceServerConfig,
    member: shared.member,
    renderedLine: shared.renderedLine,
  };

  const definitions = {};
  for (const name of ["clientMessage", "serverMessage"]) {
    const part = zodToJsonSchema(shared[name], {
      name,
      definitions: named,
      target: "jsonSchema7",
      // A transform's INPUT is what travels on the wire; the output is only what the server
      // holds after cleaning it.
      effectStrategy: "input",
      // zod STRIPS unknown keys rather than refusing them, so a frame carrying a field this
      // version does not know is still valid. Saying additionalProperties: false would make the
      // schema stricter than the parser it describes.
      removeAdditionalStrategy: "strict",
    });
    for (const [key, schema] of Object.entries(part.definitions)) {
      const text = JSON.stringify(sortKeys(schema));
      if (key in definitions && JSON.stringify(definitions[key]) !== text) {
        throw new Error(`definition ${key} generated differently for ${name}`);
      }
      definitions[key] = sortKeys(schema);
    }
  }

  const document = {
    $schema: "http://json-schema.org/draft-07/schema#",
    title: "Translatv WebSocket wire protocol",
    description:
      "GENERATED by script/gen_wire.mjs from shared/src/protocol.ts. Do not edit by hand. " +
      "Every frame is a JSON object discriminated on `t`: clientMessage is what a client sends, " +
      "serverMessage is what the server sends.",
    protocolVersion: shared.PROTOCOL_VERSION,
    definitions,
  };
  return JSON.stringify(sortKeys(document), null, 2) + "\n";
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const text = await generateSchemaText();
  mkdirSync(WIRE, { recursive: true });
  writeFileSync(join(WIRE, "schema.json"), text, "utf8");
  console.log(`wrote ${join("shared", "wire", "schema.json")}`);
}
